# Generated by Django 3.2.5 on 2021-10-18 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_interest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
